language: python
python:
# - "3.4"   # fails on travis
# - "3.5"   # fails on travis
- "3.6"
- "3.7"
- "3.8"

install:
  - pip install  .
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov

# before_install:

# cache: pip
script:
  # - pytest
    - python3 -m pytest --cov-report xml --cov=.

after_success:
  # - codecov
  - bash <(curl -s https://codecov.io/bash) -v
