name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', 'pypy-3.6']
        exclude:
          - os: macos-latest
            python-version: '3.8'
          - os: windows-latest
            python-version: '3.6'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install miditapyr
      - name: Run tests with pytest
        run: pytest
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
